comp_decrypt_tool_path = "C:/Program Files/COMP_hack/comp_decrypt.exe"
comp_bdpatch_tool_path = "C:/Program Files/COMP_hack/comp_bdpatch.exe"
base_client_binary_data_directory = "C:/Program Files/COMP_hack/client/BinaryData/Shield"
base_output_directory_xml_or_tsv = "C:/Users/Rubito/Megaten Files/scripting/extractor/extracted_xml"
base_tokusei_server_files_directory = "C:/Program Files/COMP_hack/datastore/data/tokusei"