affinities = {
  0: "NONE",
  1: "WE(A)PON",
  2: "SLASH",
  3: "CHARGE",
  4: "BLUNT",
  5: "HANDGUN",
  6: "PENETRATE",
  7: "SPREAD",
  8: "FIRE",
  9: "ICE",
  10: "ELEC",
  11: "ALMIGHTY",
  12: "FORCE",
  13: "EXPEL",
  14: "CURSE",
  15: "CURATIVE",
  16: "SUPPORT",
  17: "MYSTIC",
  18: "NERVE",
  19: "MIND",
  20: "KOTODAMA",
  21: "SPECIAL",
  22: "SUICIDE"
}